### ISSUE TITLE
authentication failed for gitlab in android studio

### ISSUE THREAD

**Issue by mojtabashirkhani** [jadijadi/gittutorial#5]
سلام ببخشید وقتتون رو میگیرم:)
دلیلش چی میتونه باشه؟
موقعی که میخواد یو آر ال رو چک کنه چنین اروری میده یعنی اوکی رو بده مثلا میتونم یه کامیت بکنم و قبلش به نظرم مشکلی وجود نداشته

**Comment by jadijadi** [comment]
سلام (: مجتبی عزیز من نمی رسم به حل مشکلات در ایمیل (: دارم سعی می کنم به
کلیت ایمیل ها برسم (: باید توی فروم ها و سرچ و اینها دنبال جواب بگردی.

جادی

**Comment by mojtabashirkhani** [comment]
اوکی زورم رو میزنم:)

**Comment by mojtabashirkhani** [comment]
ولی قبلش سرچ کرده بودم:/

**Comment by Baghlani** [comment]
i copied this from stackoverflow. ->

just copy git scm to your programfiles and do not install it,then execute bash from it. if authentication not pass yet,you should install certificate files in Program Files>>Git>>mingw64>>ssl>>certs

**Comment by mojtabashirkhani** [comment]
tnx sir:)
i test it soon;)
