### ISSUE TITLE
آموزش gitignore

### ISSUE THREAD

**Issue by Hossein-Fazel** [jadijadi/gittutorial#612]
@jadijadi 
سلام بر استاد جادی عزیز 
من یکی از دانشجویان دوره ی گیت شما هستم. دوره تون واقعا فوق العاده بود، شیوه ی تدریس، لحن تدریس، تسلط بر مطالب، زمان هر جلسه و.... عالی بودند. من که خیلی لذت بردم.
اگه براتون ممکنه و صلاح می دونید، یه بخش دیگه به دوره اضافه کنید و در آن _gitignore_ را تدریس کنید. باز هم ممنون

**Comment by amirroox** [comment]
سلام دوست من 
میتونی از این لینک ها هم استفاده کنی <hr/>
 

<a href="https://roocket.ir/series/learn-git-and-github">سایت راکت </a>
<a href="https://sokanacademy.com/academy/courses/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1%D8%AF%DB%8C-%DA%AF%DB%8C%D8%AA-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%D8%A7%D9%86/%D8%B4%D8%B1%D9%88%D8%B9-%DA%A9%D8%A7%D8%B1-%D8%A8%D8%A7-%DA%AF%DB%8C%D8%AA/gitignore-%DA%86%DB%8C%D8%B3%D8%AA"> سایت سکان آکادمی </a>
<a href="https://www.w3schools.com/git/git_ignore.asp" > W3Schools </a>
<a href="https://git-scm.com/docs/gitignore"> Main Dacumation </a>
:)

**Comment by Hossein-Fazel** [comment]
> سلام دوست من میتونی از این لینک ها هم استفاده کنی
> 
> [سایت راکت ](https://roocket.ir/series/learn-git-and-github) [ سایت سکان آکادمی ](https://sokanacademy.com/academy/courses/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1%D8%AF%DB%8C-%DA%AF%DB%8C%D8%AA-%D8%A8%D8%B1%D8%A7%DB%8C-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%D8%A7%D9%86/%D8%B4%D8%B1%D9%88%D8%B9-%DA%A9%D8%A7%D8%B1-%D8%A8%D8%A7-%DA%AF%DB%8C%D8%AA/gitignore-%DA%86%DB%8C%D8%B3%D8%AA) [ W3Schools ](https://www.w3schools.com/git/git_ignore.asp) [ Main Dacumation ](https://git-scm.com/docs/gitignore) :)

متشکرم 🙏
